apiVersion: v1
kind: Secret
metadata:
  name: procrush-secret
  namespace: procrush
type: Opaque
stringData:
  DATABASE_PASSWORD: procrush
  MATCHING_DATABASE_PASSWORD: procrush
  RABBITMQ_DEFAULT_USER: procrush
  RABBITMQ_DEFAULT_PASS: procrush
  LLM_API_KEY: "AQ.Ab8RN6JrJUjriZVKb3Pfc1y5Kis5ByrtXl6kYFSt2D63vFz7IA" # todo: remove
