services:
  postgres:
    container_name: procrush-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: procrush
      POSTGRES_USER: procrush
      POSTGRES_PASSWORD: procrush
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    container_name: procrush-redis
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    name: procrush-postgres-data
  redis_data:
    name: procrush-redis-data
